# -*- coding: utf-8 -*-
"""dio_operacoes_bancarias.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KvW3a2jP7UNuQ8gYegTvfHKzvZZYSL3A
"""

def operacoes(saldo, movimentacoes, saques_diarios, sessao_ativa):
  while sessao_ativa == True:
    op = escolhe_operacao()

    if(op == "X"):
      sessao_ativa = False
      break

    match op:
      case "D":
        saldo, movimentacoes = deposito(saldo, movimentacoes)
      case "E":
        extrato(saldo, movimentacoes)
      case "S":
        saldo, movimentacoes, saques_diarios = saque(saldo, movimentacoes, saques_diarios)

  return(saldo)

def escolhe_operacao():
  op = input(
  """
  Qual operação deseja realizar?
  [D] Depósito
  [E] Extrato
  [S] Saque
  [X] Sair
  """).upper()

  if(not op in ["D","E","S","X"]):
    return(False)
  else:
    return(op)

def deposito(saldo, movimentacoes):

  while True:
    try:
      valor_deposito = float(input("Qual o valor a ser depositado?"))
      break
    except:
      print("Valor inválido, tente novamente!")

  movimentacoes.append(valor_deposito)
  saldo_novo = saldo + valor_deposito

  return(saldo_novo, movimentacoes)

def extrato(saldo, movimentacoes):
  
  for mov in range(0, len(movimentacoes)):
    print("R$ ",str(movimentacoes[mov]))

  print(f"Seu saldo disponível é R$ {float(saldo)}")

def saque(saldo, movimentacoes, saques_diarios):

  if(saques_diarios == 0):
    print("Limite de saques diários excedido")
    return(saldo, movimentacoes, saques_diarios)

  while True:
    try:
      valor_saque = float(input("Qual o valor a ser sacado? (limite de R$ 500,00 por saque)"))

      if(valor_saque > 500):
        print("Valor acima do limite pertimitido.")
        continue

      if(valor_saque > saldo):
        print("Saldo insuficiiente.")
        continue

      break
    except:
      print("Valor inválido, tente novamente!")
    
  movimentacoes.append(-valor_saque)
  saldo_novo = saldo - valor_saque
  saques_diarios-=1
  return(saldo_novo, movimentacoes, saques_diarios)

saldo = 0
movimentacoes = []
sessao_ativa = True
saques_diarios = 3


saldo = operacoes(saldo, movimentacoes, saques_diarios, sessao_ativa)